basic.forever(function () {
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(10)
    music.playTone(349, music.beat(BeatFraction.Whole))
})
